language: ruby
rvm:
  - 2.3.3

before_install:
  - nvm install 7
  - npm install
  
install:
  - npm install -g firebase-tools

script:
  - npm run build
  - npm run precache

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
